/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380.jhinze;

import java.awt.Color;

/**
 *
 * @author lk0
 */
public class TextEditorTabPanel extends javax.swing.JPanel {
    private int id;
    private String title;
    /**
     * Creates new form viewTabPanel
     */
    public TextEditorTabPanel(String title, int id) {
        this.id = id;
        this.title = title;
        initComponents();
        labelTabPanel.setText(title);
        this.setOpaque(false);
    }
    
    public String getUID() {
        return title +"" +id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTabPanel = new javax.swing.JButton();
        labelTabPanel = new javax.swing.JLabel();
        labelClose = new javax.swing.JLabel();

        buttonTabPanel.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        buttonTabPanel.setText("X");

        labelTabPanel.setText("jLabel1");

        labelClose.setBackground(new java.awt.Color(204, 204, 204));
        labelClose.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        labelClose.setForeground(new java.awt.Color(204, 0, 0));
        labelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClose.setText("X");
        labelClose.setToolTipText("CLOSE");
        labelClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelClose.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelTabPanel)
                .addComponent(labelClose))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTabPanel;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelTabPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the buttonTabPanel
     */
    public javax.swing.JButton getButtonTabPanel() {
        return buttonTabPanel;
    }

    /**
     * @return the labelTabPanel
     */
    public javax.swing.JLabel getLabelTabPanel() {
        return labelTabPanel;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @return the labelClose
     */
    public javax.swing.JLabel getLabelClose() {
        return labelClose;
    }
}
