/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380.jhinze;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author lk0
 */
public class TextEditorClientGUI extends javax.swing.JFrame {

    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode treeRoot;
    private JFileChooser fileChooser;

    /**
     * Creates new form TextEditorClientGUI
     */
    public TextEditorClientGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(TextEditorClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        treeModel = (DefaultTreeModel) treeFileStructure.getModel();
        treeRoot = (DefaultMutableTreeNode) treeModel.getRoot();
        treeRoot.removeAllChildren();
        treeRoot.setUserObject("..");
        treeModel.nodeStructureChanged(treeRoot);
        ((DefaultTreeCellRenderer) treeFileStructure.getCellRenderer())
                .setLeafIcon(javax.swing.UIManager.getIcon("FileView.fileIcon"));
        fileChooser = new JFileChooser();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (screen.getWidth() - getWidth()) / 2,
                (int) (screen.getHeight() - getHeight()) / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuFileTree = new javax.swing.JPopupMenu();
        menuItemTreeOpen = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuItemTreeNewFile = new javax.swing.JMenuItem();
        menuItemTreeNewDirectory = new javax.swing.JMenuItem();
        menuItemTreeDelete = new javax.swing.JMenuItem();
        menuItemTreeRename = new javax.swing.JMenuItem();
        menuItemTreeHome = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemTreeUpload = new javax.swing.JMenuItem();
        menuItemTreeDownload = new javax.swing.JMenuItem();
        panelControlArea = new javax.swing.JPanel();
        toolBarMain = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        textFieldHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordFieldPassword = new javax.swing.JPasswordField();
        buttonConnect = new javax.swing.JButton();
        buttonDisconnect = new javax.swing.JButton();
        splitPaneMain = new javax.swing.JSplitPane();
        scrollPaneTreeContainer = new javax.swing.JScrollPane();
        treeFileStructure = new javax.swing.JTree();
        textEditorPanel = new csc4380.jhinze.TextEditorPanel();
        menuBarMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemClose = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuItemNewFile = new javax.swing.JMenuItem();
        menuItemNewDirectory = new javax.swing.JMenuItem();
        menuItemFileDelete = new javax.swing.JMenuItem();
        menuItemRename = new javax.swing.JMenuItem();
        menuItemHome = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuItemUpload = new javax.swing.JMenuItem();
        menuItemDownload = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemUndo = new javax.swing.JMenuItem();
        menuItemRedo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemCut = new javax.swing.JMenuItem();
        menuItemCopy = new javax.swing.JMenuItem();
        menuItemPaste = new javax.swing.JMenuItem();
        menuItemDelete = new javax.swing.JMenuItem();
        menuItemSelectAll = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuItemSearch = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuItemAppearance = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        menuItemTreeOpen.setText("Open");
        popupMenuFileTree.add(menuItemTreeOpen);
        popupMenuFileTree.add(jSeparator7);

        menuItemTreeNewFile.setText("New File");
        popupMenuFileTree.add(menuItemTreeNewFile);

        menuItemTreeNewDirectory.setText("New Directory");
        popupMenuFileTree.add(menuItemTreeNewDirectory);

        menuItemTreeDelete.setText("Delete");
        popupMenuFileTree.add(menuItemTreeDelete);

        menuItemTreeRename.setText("Rename");
        popupMenuFileTree.add(menuItemTreeRename);

        menuItemTreeHome.setText("Home Dir");
        popupMenuFileTree.add(menuItemTreeHome);
        popupMenuFileTree.add(jSeparator3);

        menuItemTreeUpload.setText("Upload");
        popupMenuFileTree.add(menuItemTreeUpload);

        menuItemTreeDownload.setText("Download");
        popupMenuFileTree.add(menuItemTreeDownload);

        panelControlArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelControlArea.setMaximumSize(new java.awt.Dimension(162, 592));
        panelControlArea.setPreferredSize(new java.awt.Dimension(1440, 599));

        javax.swing.GroupLayout panelControlAreaLayout = new javax.swing.GroupLayout(panelControlArea);
        panelControlArea.setLayout(panelControlAreaLayout);
        panelControlAreaLayout.setHorizontalGroup(
            panelControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        panelControlAreaLayout.setVerticalGroup(
            panelControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("sftp Text Editor Client - Final Project");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));

        toolBarMain.setFloatable(false);
        toolBarMain.setRollover(true);

        jLabel5.setText("Status: ");
        toolBarMain.add(jLabel5);

        labelStatus.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelStatus.setText("Not Connected");
        labelStatus.setMaximumSize(new java.awt.Dimension(100, 14));
        labelStatus.setMinimumSize(new java.awt.Dimension(100, 14));
        labelStatus.setPreferredSize(new java.awt.Dimension(100, 14));
        toolBarMain.add(labelStatus);
        toolBarMain.add(jSeparator2);

        jLabel1.setText(" Host:");
        toolBarMain.add(jLabel1);

        textFieldHost.setMaximumSize(new java.awt.Dimension(120, 24));
        textFieldHost.setMinimumSize(new java.awt.Dimension(40, 24));
        textFieldHost.setPreferredSize(new java.awt.Dimension(120, 24));
        toolBarMain.add(textFieldHost);

        jLabel2.setText(" Port:");
        toolBarMain.add(jLabel2);

        textFieldPort.setMaximumSize(new java.awt.Dimension(30, 24));
        textFieldPort.setMinimumSize(new java.awt.Dimension(20, 24));
        textFieldPort.setPreferredSize(new java.awt.Dimension(30, 24));
        toolBarMain.add(textFieldPort);

        jLabel3.setText(" User Name:");
        toolBarMain.add(jLabel3);

        textFieldUserName.setMaximumSize(new java.awt.Dimension(120, 24));
        textFieldUserName.setMinimumSize(new java.awt.Dimension(40, 24));
        textFieldUserName.setPreferredSize(new java.awt.Dimension(120, 24));
        toolBarMain.add(textFieldUserName);

        jLabel4.setText(" Password:");
        toolBarMain.add(jLabel4);

        passwordFieldPassword.setMaximumSize(new java.awt.Dimension(120, 24));
        passwordFieldPassword.setMinimumSize(new java.awt.Dimension(40, 24));
        passwordFieldPassword.setPreferredSize(new java.awt.Dimension(120, 24));
        toolBarMain.add(passwordFieldPassword);

        buttonConnect.setText("Connect");
        toolBarMain.add(buttonConnect);

        buttonDisconnect.setText("Disconnect");
        buttonDisconnect.setFocusable(false);
        buttonDisconnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDisconnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarMain.add(buttonDisconnect);

        getContentPane().add(toolBarMain, java.awt.BorderLayout.PAGE_START);

        splitPaneMain.setBorder(null);
        splitPaneMain.setDividerLocation(175);
        splitPaneMain.setRequestFocusEnabled(false);

        scrollPaneTreeContainer.setViewportView(treeFileStructure);

        splitPaneMain.setLeftComponent(scrollPaneTreeContainer);

        textEditorPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textEditorPanel.setToolTipText("CTRL + F");
        splitPaneMain.setRightComponent(textEditorPanel);

        getContentPane().add(splitPaneMain, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemSave.setText("Save");
        menuFile.add(menuItemSave);

        menuItemClose.setText("Close");
        menuFile.add(menuItemClose);
        menuFile.add(jSeparator6);

        menuItemNewFile.setText("New File");
        menuItemNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewFileActionPerformed(evt);
            }
        });
        menuFile.add(menuItemNewFile);

        menuItemNewDirectory.setText("New Directory");
        menuFile.add(menuItemNewDirectory);

        menuItemFileDelete.setText("Delete");
        menuFile.add(menuItemFileDelete);

        menuItemRename.setText("Rename");
        menuFile.add(menuItemRename);

        menuItemHome.setText("Home Dir");
        menuFile.add(menuItemHome);
        menuFile.add(jSeparator5);

        menuItemUpload.setText("Upload");
        menuFile.add(menuItemUpload);

        menuItemDownload.setText("Download");
        menuFile.add(menuItemDownload);
        menuFile.add(jSeparator1);

        menuItemExit.setText("Exit");
        menuFile.add(menuItemExit);

        menuBarMain.add(menuFile);

        menuEdit.setText("Edit");

        menuItemUndo.setText("Undo");
        menuEdit.add(menuItemUndo);

        menuItemRedo.setText("Redo");
        menuEdit.add(menuItemRedo);
        menuEdit.add(jSeparator4);

        menuItemCut.setText("Cut");
        menuEdit.add(menuItemCut);

        menuItemCopy.setText("Copy");
        menuEdit.add(menuItemCopy);

        menuItemPaste.setText("Paste");
        menuEdit.add(menuItemPaste);

        menuItemDelete.setText("Delete");
        menuEdit.add(menuItemDelete);

        menuItemSelectAll.setText("Select All");
        menuEdit.add(menuItemSelectAll);
        menuEdit.add(jSeparator8);

        menuItemSearch.setText("Search");
        menuEdit.add(menuItemSearch);

        menuBarMain.add(menuEdit);

        menuView.setText("View");

        menuItemAppearance.setText("Appearance");
        menuView.add(menuItemAppearance);

        menuBarMain.add(menuView);

        menuHelp.setText("Help");

        menuItemAbout.setText("About");
        menuHelp.add(menuItemAbout);

        menuBarMain.add(menuHelp);

        setJMenuBar(menuBarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuItemNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemNewFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnect;
    private javax.swing.JButton buttonDisconnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemAppearance;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemCopy;
    private javax.swing.JMenuItem menuItemCut;
    private javax.swing.JMenuItem menuItemDelete;
    private javax.swing.JMenuItem menuItemDownload;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemFileDelete;
    private javax.swing.JMenuItem menuItemHome;
    private javax.swing.JMenuItem menuItemNewDirectory;
    private javax.swing.JMenuItem menuItemNewFile;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemPaste;
    private javax.swing.JMenuItem menuItemRedo;
    private javax.swing.JMenuItem menuItemRename;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSearch;
    private javax.swing.JMenuItem menuItemSelectAll;
    private javax.swing.JMenuItem menuItemTreeDelete;
    private javax.swing.JMenuItem menuItemTreeDownload;
    private javax.swing.JMenuItem menuItemTreeHome;
    private javax.swing.JMenuItem menuItemTreeNewDirectory;
    private javax.swing.JMenuItem menuItemTreeNewFile;
    private javax.swing.JMenuItem menuItemTreeOpen;
    private javax.swing.JMenuItem menuItemTreeRename;
    private javax.swing.JMenuItem menuItemTreeUpload;
    private javax.swing.JMenuItem menuItemUndo;
    private javax.swing.JMenuItem menuItemUpload;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel panelControlArea;
    private javax.swing.JPasswordField passwordFieldPassword;
    private javax.swing.JPopupMenu popupMenuFileTree;
    private javax.swing.JScrollPane scrollPaneTreeContainer;
    private javax.swing.JSplitPane splitPaneMain;
    private csc4380.jhinze.TextEditorPanel textEditorPanel;
    private javax.swing.JTextField textFieldHost;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldUserName;
    private javax.swing.JToolBar toolBarMain;
    private javax.swing.JTree treeFileStructure;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the buttonConnect
     */
    public javax.swing.JButton getButtonConnect() {
        return buttonConnect;
    }

    /**
     * @return the buttonDisconnect
     */
    public javax.swing.JButton getButtonDisconnect() {
        return buttonDisconnect;
    }


    /**
     * @return the textFieldHost
     */
    public javax.swing.JTextField getTextFieldHost() {
        return textFieldHost;
    }

    /**
     * @return the textFieldPort
     */
    public javax.swing.JTextField getTextFieldPort() {
        return textFieldPort;
    }

    /**
     * @return the textFieldUserName
     */
    public javax.swing.JTextField getTextFieldUserName() {
        return textFieldUserName;
    }

    /**
     * @return the treeFileStructure
     */
    public javax.swing.JTree getTreeFileStructure() {
        return treeFileStructure;
    }

    /**
     * @return the passwordFieldPassword
     */
    public javax.swing.JPasswordField getPasswordFieldPassword() {
        return passwordFieldPassword;
    }

    /**
     * @return the MenuItemUpload
     */
    public javax.swing.JMenuItem getMenuItemUpload() {
        return menuItemUpload;
    }

    /**
     * @return the menuItemAbout
     */
    public javax.swing.JMenuItem getMenuItemAbout() {
        return menuItemAbout;
    }

    /**
     * @return the menuItemDownload
     */
    public javax.swing.JMenuItem getMenuItemDownload() {
        return menuItemDownload;
    }

    /**
     * @return the menuItemExit
     */
    public javax.swing.JMenuItem getMenuItemExit() {
        return menuItemExit;
    }

    /**
     * @return the labelStatus
     */
    public javax.swing.JLabel getLabelStatus() {
        return labelStatus;
    }


    /**
     * @param treeFileStructure the treeFileStructure to set
     */
    public void setTreeFileStructure(javax.swing.JTree treeFileStructure) {
        this.treeFileStructure = treeFileStructure;
    }

    /**
     * @return the scrollPaneTreeContainer
     */
    public javax.swing.JScrollPane getScrollPaneTreeContainer() {
        return scrollPaneTreeContainer;
    }

    /**
     * @param scrollPaneTreeContainer the scrollPaneTreeContainer to set
     */
    public void setScrollPaneTreeContainer(javax.swing.JScrollPane scrollPaneTreeContainer) {
        this.scrollPaneTreeContainer = scrollPaneTreeContainer;
    }

    /**
     * @return the treeModel
     */
    public DefaultTreeModel getTreeModel() {
        return treeModel;
    }

    /**
     * @param treeModel the treeModel to set
     */
    public void setTreeModel(DefaultTreeModel treeModel) {
        this.treeModel = treeModel;
    }

    /**
     * @return the treeRoot
     */
    public DefaultMutableTreeNode getTreeRoot() {
        return treeRoot;
    }

    /**
     * @param treeRoot the treeRoot to set
     */
    public void setTreeRoot(DefaultMutableTreeNode treeRoot) {
        this.treeRoot = treeRoot;
    }

    /**
     * @return the fileChooser
     */
    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    /**
     * @return the menuItemClose
     */
    public javax.swing.JMenuItem getMenuItemClose() {
        return menuItemClose;
    }

    /**
     * @return the menuItemCopy
     */
    public javax.swing.JMenuItem getMenuItemCopy() {
        return menuItemCopy;
    }

    /**
     * @return the menuItemCut
     */
    public javax.swing.JMenuItem getMenuItemCut() {
        return menuItemCut;
    }

    /**
     * @return the menuItemDelete
     */
    public javax.swing.JMenuItem getMenuItemDelete() {
        return menuItemDelete;
    }

    /**
     * @return the menuItemPaste
     */
    public javax.swing.JMenuItem getMenuItemPaste() {
        return menuItemPaste;
    }

    /**
     * @return the menuItemRedo
     */
    public javax.swing.JMenuItem getMenuItemRedo() {
        return menuItemRedo;
    }

    /**
     * @return the menuItemSave
     */
    public javax.swing.JMenuItem getMenuItemSave() {
        return menuItemSave;
    }

    /**
     * @return the menuItemSelectAll
     */
    public javax.swing.JMenuItem getMenuItemSelectAll() {
        return menuItemSelectAll;
    }

    /**
     * @return the menuItemTreeDelete
     */
    public javax.swing.JMenuItem getMenuItemTreeDelete() {
        return menuItemTreeDelete;
    }

    /**
     * @return the menuItemTreeDownload
     */
    public javax.swing.JMenuItem getMenuItemTreeDownload() {
        return menuItemTreeDownload;
    }

    /**
     * @return the menuItemTreeNew
     */
    public javax.swing.JMenuItem getMenuItemTreeNew() {
        return getMenuItemTreeNewFile();
    }

    /**
     * @return the menuItemTreeOpen
     */
    public javax.swing.JMenuItem getMenuItemTreeOpen() {
        return menuItemTreeOpen;
    }

    /**
     * @return the menuItemTreeUpload
     */
    public javax.swing.JMenuItem getMenuItemTreeUpload() {
        return menuItemTreeUpload;
    }

    /**
     * @return the menuItemUndo
     */
    public javax.swing.JMenuItem getMenuItemUndo() {
        return menuItemUndo;
    }

    /**
     * @return the popupMenuFileTree
     */
    public javax.swing.JPopupMenu getPopupMenuFileTree() {
        return popupMenuFileTree;
    }

    /**
     * @return the textEditorPanel
     */
    public csc4380.jhinze.TextEditorPanel getTextEditorPanel() {
        return textEditorPanel;
    }

    /**
     * @return the menuItemOpen
     */
    public javax.swing.JMenuItem getMenuItemOpen() {
        return menuItemOpen;
    }

    /**
     * @return the menuItemFileDelete
     */
    public javax.swing.JMenuItem getMenuItemFileDelete() {
        return menuItemFileDelete;
    }

    /**
     * @return the menuItemNew
     */
    public javax.swing.JMenuItem getMenuItemNew() {
        return getMenuItemNewFile();
    }

    /**
     * @return the menuItemNewDirectory
     */
    public javax.swing.JMenuItem getMenuItemNewDirectory() {
        return menuItemNewDirectory;
    }

    /**
     * @return the menuItemNewFile
     */
    public javax.swing.JMenuItem getMenuItemNewFile() {
        return menuItemNewFile;
    }

    /**
     * @return the menuItemTreeNewDirectory
     */
    public javax.swing.JMenuItem getMenuItemTreeNewDirectory() {
        return menuItemTreeNewDirectory;
    }

    /**
     * @return the menuItemTreeNewFile
     */
    public javax.swing.JMenuItem getMenuItemTreeNewFile() {
        return menuItemTreeNewFile;
    }


    /**
     * @return the menuItemRename
     */
    public javax.swing.JMenuItem getMenuItemRename() {
        return menuItemRename;
    }

    /**
     * @return the menuItemTreeRename
     */
    public javax.swing.JMenuItem getMenuItemTreeRename() {
        return menuItemTreeRename;
    }

    /**
     * @return the menuItemHome
     */
    public javax.swing.JMenuItem getMenuItemHome() {
        return menuItemHome;
    }

    /**
     * @return the menuItemTreeHome
     */
    public javax.swing.JMenuItem getMenuItemTreeHome() {
        return menuItemTreeHome;
    }

    /**
     * @return the menuItemAppearance
     */
    public javax.swing.JMenuItem getMenuItemAppearance() {
        return menuItemAppearance;
    }

    /**
     * @return the menuItemSearch
     */
    public javax.swing.JMenuItem getMenuItemSearch() {
        return menuItemSearch;
    }

}
